### ISSUE TITLE
Fish can be thrown off the boat/ New task?

### ISSUE THREAD

**Issue by SnorreForbregd** [vr4vet/Blue-Sector#194]
The fish in the Fish Welfare game can be thrown off the boat and into the water. 

A proposed addition to the Fish Welfare game would be a step before the current game to pick up the fish from the merds, and a step to throw it back into the merd after the game is done.

**Comment by fominykh** [comment]
Throwing fish overboard is OK. No need to do anything about it.
Fish welfare content scenario should be completely reworked, so that we have clear steps of the procedure, including catching fish from the cage first and releasing them afterwards back to the cage.
So, we need to add a teleport to the cage surface and back to the inspection boat.

**Comment by eamathie** [comment]
Fish and anesthetic bottle respawn on boat after issue #345 was merged.
