### ISSUE TITLE
Fix bugs from levels

### ISSUE THREAD

**Issue by qlpham231** [vr4vet/Blue-Sector#94]
- [ ] Fix bugs/errors given from levels when playing the game

**Comment by torjacob** [comment]
Unless I'm mistaken this is not an issue.

Assuming levels means the modes component in this context, given deprecation of levels in commit  5f46ad0.
In this commit, Levelloader and all other level functions were moved to modeloader etc in the "Modes" subfolder in FishFeeding/Components.

In the fork used for demoing the project last Friday, this Mode folder is not present - and only FishFeeding/'LevelSystem' (its previous location) is in the repo.

In essence this seems to have become an issue due to mistakes being made in the forking process / when moving mode-related code.

As a result the demo given on Friday did not have an up to date codebase around this feature. And likely gave a false impression of its completeness.

Feel free to reopen the issue if I've misunderstood, but for now I'll close it.

**Comment by torjacob** [comment]
Newest change on this feature: #90 / [8c1c688](https://github.com/vr4vet/Blue-Sector/pull/90/commits/8c1c688dbfa6ddc6f405f2b128defcf0e22cb76a)
